const userInput=require('readline-sync');
let digit=userInput.questionInt("Enter the number  : ");
console.log(digit);
if (digit==1) console.log("Monday");
else if (digit==2)console.log("Tuesday");
else if (digit==3)console.log("Wednesday");
else if (digit==4)console.log("Thursday");
else if (digit==5)console.log("Friday");
else if (digit==6)console.log("Saturday");
else if (digit==7)console.log("Sunday");
else console.log("No more days than seven in a week");